services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: supabase-db
          property: connectionString

databases:
  - name: supabase-db
    plan: free